# Hacktiv8 Phase 0: Non Graded Challenge 3

---

By [Rifky Aliffa](https://github.com/Penzragon)

Instruction:

1. Buatlah vektor di bawah ini dengan Python:

   ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bpmatrix%7D17%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bpmatrix%7D)

2. Diberikan 3 buah vector 3 dimensi:

   ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20A%20%3D%20%5Cbegin%7Bpmatrix%7D17%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bpmatrix%7D%2C%20B%20%3D%20%5Cbegin%7Bpmatrix%7D10%20%5C%5C%2020%20%5C%5C%2011%20%5Cend%7Bpmatrix%7D%20C%20%3D%20%5Cbegin%7Bpmatrix%7D5%20%5C%5C%2012%20%5C%5C%209%20%5Cend%7Bpmatrix%7D)

   Hitunglah:

   - A + B
   - B - C
   - A dot C
   - A x B
   - norm A
   - Sudut antara vektor A dan B

3. Buatlah plot dari vector berikut ini ke dalam bidang 2D:

   ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20u%20%3D%20%5Cbinom%7B2%7D%7B5%7D%2C%20v%20%3D%20%5Cbinom%7B3%7D%7B1%7D)


## Import Library

In [1]:
import numpy as np

## Answer

### 1. Buatlah vektor di bawah ini dengan Python:

   ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20%5Cbegin%7Bpmatrix%7D17%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bpmatrix%7D)

In [3]:
np.array([17, 22, 19])

array([17, 22, 19])

### 2. Diberikan 3 buah vector 3 dimensi:

   ![Vector](https://latex.codecogs.com/gif.latex?%5Cinline%20A%20%3D%20%5Cbegin%7Bpmatrix%7D17%20%5C%5C%2022%20%5C%5C%2019%20%5Cend%7Bpmatrix%7D%2C%20B%20%3D%20%5Cbegin%7Bpmatrix%7D10%20%5C%5C%2020%20%5C%5C%2011%20%5Cend%7Bpmatrix%7D%20C%20%3D%20%5Cbegin%7Bpmatrix%7D5%20%5C%5C%2012%20%5C%5C%209%20%5Cend%7Bpmatrix%7D)

In [4]:
a = np.array([17, 22, 19])
b = np.array([10, 20, 11])
c = np.array([5, 12, 9])

print(f'Vektor A: {a}')
print(f'Vektor B: {b}')
print(f'Vektor C: {c}')

Vektor A: [17 22 19]
Vektor B: [10 20 11]
Vektor C: [ 5 12  9]


#### Hitunglah A + B

In [5]:
a + b

array([27, 42, 30])

#### Hitunglah B - C

In [6]:
b - c

array([5, 8, 2])

#### Hitunglah A dot C

In [7]:
np.dot(a, c)

520

#### Hitunglah A * B

In [8]:
a * b

array([170, 440, 209])

#### Hitunglah norm A

In [15]:
print(f'Menggunakan Euclidean Distance: {np.linalg.norm(a)}')
print(f'Menggunakan Manhattan Distance: {np.linalg.norm(a, 1)}')

Menggunakan Euclidean Distance: 33.67491648096547
Menggunakan Manhattan Distance: 58.0


#### Hitunglah sudut antara A dan B

In [12]:
cos_theta = (a@b) / (np.linalg.norm(a) * np.linalg.norm(b))
rad = np.arccos(cos_theta)
degree = np.degrees(rad)
print(f'Sudut antara A dan B adalah {degree:.2f}')

Sudut antara A dan B adalah 12.59
